version: 0.2

phases:

  install:
    commands:

      - echo "install npm v5.3.0"
      - npm install -g npm@5.3.0

      - echo "install local dependancies"
      - npm install

  pre_build:
    commands:

      - echo "access id = $AWS_ACCESS_KEY_ID"
      - echo "access key = $AWS_SECRET_ACCESS_KEY"

      # - echo "run tests (linting + unit)"
      # - npm test

  build:
    commands:

      - echo "create webpack (production) build"
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY npm run webpack -- -p

  post_build:
    commands:

      - echo "deploy lambda(s)"
      - npm run serverless deploy -- -v
